[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 921600
upload_speed = 921600
upload_port = /dev/cu.usbmodem11101
monitor_port = /dev/cu.usbmodem11101
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D MIC_SAMPLE_RATE=16000
  -D MIC_FRAME_SAMPLES=320
  -D MIC_SAMPLE_SHIFT=11
  -D I2S_BCLK_PIN=5
  -D I2S_LRCLK_PIN=4
  -D I2S_DATA_PIN=6
